"""
Django settings for ssMonitoringProjectDJ project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file from the project root (one level up from Django project)
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-3g1p-1hqh--r6qna3a#_@hsu!ghp(u=^0jfpxtn75ce9g&8d8e')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_crontab',
    "solarData",
    "solarDataFetch",
    "solarDataStore",
    "solarDataNewSystem",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ssMonitoringProjectDJ.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ssMonitoringProjectDJ.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'ssmonitoring'),
        'USER': os.environ.get('DB_USER', 'ssuser'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'sspassword'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

# Django Logging Configuration for CloudWatch
# This sets up logging that writes to files, which CloudWatch Agent automatically picks up
LOGGING = {
    # Always use version 1 for Django logging configuration
    'version': 1,
    
    # Keep Django's existing loggers (don't disable them)
    'disable_existing_loggers': False,
    
    # FORMATTERS: Define how log messages should look
    'formatters': {
        'simple': {
            # Format: "2025-01-15 10:30:15 INFO huawei_fetcher Starting login attempt"
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',  # Use new-style string formatting
        },
    },
    
    # HANDLERS: Define where logs should go
    'handlers': {
        # FILE HANDLER: Writes logs to a file (CloudWatch Agent reads this file)
        'file': {
            'level': 'INFO',  # Only log INFO level and above
            'class': 'logging.FileHandler',  # Write to file
            'filename': BASE_DIR.parent / 'logs' / 'django.log',  # Windows-compatible path
            'formatter': 'simple',  # Use the 'simple' formatter defined above
        },
        
        # CONSOLE HANDLER: Prints logs to terminal/console (for debugging)
        'console': {
            'level': 'INFO',  # Only log INFO level and above
            'class': 'logging.StreamHandler',  # Print to stdout/stderr
            'formatter': 'simple',  # Use the 'simple' formatter defined above
        },
    },
    
    # LOGGERS: Define which code can log and how
    'loggers': {
        # Logger for Huawei fetcher code
        'huawei_fetcher': {
            'handlers': ['file', 'console'],  # Send logs to both file and console
            'level': 'INFO',  # Minimum level to log
            'propagate': False,  # Don't pass logs to parent loggers (prevents duplicates)
        },
        
        # Add more loggers here as needed:
        # 'solis_fetcher': {
        #     'handlers': ['file', 'console'],
        #     'level': 'INFO',
        #     'propagate': False,
        # },
    },
}

# LOGGING LEVELS (from lowest to highest priority):
# DEBUG    - Detailed diagnostic info (usually only when diagnosing problems)
# INFO     - General information about program execution
# WARNING  - Something unexpected happened, but program still works
# ERROR    - A serious problem occurred, some function failed
# CRITICAL - A very serious error occurred, program might stop

# Usage in your code:
# import logging
# logger = logging.getLogger('huawei_fetcher')
# logger.debug("Detailed debug info")      # Won't show (below INFO level)
# logger.info("General information")       # Will show ✅
# logger.warning("Something unexpected")   # Will show ✅
# logger.error("An error occurred")        # Will show ✅
# logger.critical("Critical failure")      # Will show ✅

# Django-Crontab Configuration
CRONJOBS = [
    # Run at 10:10 AM Colombian time (3:10 PM UTC = 15:10 UTC)
    # Format: minute hour day month day_of_week
    ('10 15 * * *', 'django.core.management.call_command', ['collect_all_gen_yesterday', '--skip-errors']),
]

# Optional: Configure command prefix for virtual environment
CRONTAB_COMMAND_PREFIX = 'cd /opt/solar-monitoring/ssMonitoringProjectDJ && source /opt/solar-monitoring/venv/bin/activate &&'

# Optional: Prevent multiple instances from running
CRONTAB_LOCK_JOBS = True

