# Generated by Django 5.2 on 2025-04-24 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_inversor', models.CharField(default='', max_length=100, verbose_name='serial del inversor')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealname', models.CharField(max_length=255, verbose_name='nombre del proyecto')),
                ('ciudad', models.CharField(max_length=100, verbose_name='ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='departamento')),
                ('energia_prometida_mes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='energía prometida en el mes')),
                ('energia_minima_mes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='energía mínima prometida en el mes')),
                ('fecha_entrada_en_operacion', models.DateField(verbose_name='fecha de entrada en operación')),
                ('restriccion_de_autoconsumo', models.BooleanField(default=False, verbose_name='tiene restricción de autoconsumo')),
            ],
            options={
                'verbose_name': 'Proyecto',
            },
        ),
        migrations.CreateModel(
            name='MPPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_mppt', models.CharField(default='', max_length=100, verbose_name='serial del mppt')),
                ('id_inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.inversor')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.proyecto', verbose_name='nombre del proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='inversor',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.proyecto', verbose_name='nombre del proyecto'),
        ),
        migrations.CreateModel(
            name='GeneracionMPPTDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energia_generada_mppt_dia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='energía por mppt generada en el día')),
                ('fecha_generacion_mppt_dia', models.DateField(verbose_name='fecha de generación por mppt')),
                ('id_inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.inversor')),
                ('id_mppt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.mppt')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.proyecto', verbose_name='nombre del proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='GeneracionInversorDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energia_generada_inversor_dia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='energía por inversor generada en el día')),
                ('fecha_generacion_inversor_dia', models.DateField(verbose_name='fecha de generación por inversor')),
                ('id_inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.inversor')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.proyecto', verbose_name='nombre del proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='GeneracionEnergiaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energia_generada_dia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='energía generada en el día')),
                ('fecha_generacion_dia', models.DateField(verbose_name='fecha de generación')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.proyecto', verbose_name='nombre del proyecto')),
            ],
        ),
    ]
