# Generated by Django 5.2 on 2025-04-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='energia_minima_mes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='energía mínima prometida en el mes'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='energia_prometida_mes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='energía prometida en el mes'),
        ),
    ]
