# Generated by Django 5.2 on 2025-04-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0002_alter_proyecto_energia_minima_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='identificador_marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='identificador de marca'),
        ),
    ]
