# Generated by Django 5.2 on 2025-04-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0003_proyecto_identificador_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcasInversores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='marca de inversor')),
            ],
            options={
                'verbose_name': 'Marca de Inversor',
            },
        ),
    ]
