# Generated by Django 5.2 on 2025-04-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0004_marcasinversores'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='marca_inversor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solarData.marcasinversores', verbose_name='marca de inversor'),
        ),
    ]
