# Generated by Django 5.2 on 2025-04-26 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0005_proyecto_marca_inversor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generacionenergiadiaria',
            unique_together={('id_proyecto', 'fecha_generacion_dia')},
        ),
    ]
