# Generated by Django 5.2 on 2025-04-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0006_alter_generacionenergiadiaria_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inversor',
            old_name='serial_inversor',
            new_name='identificador_inversor',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='identificador_marca',
            new_name='identificador_planta',
        ),
    ]
