# Generated by Django 5.2 on 2025-04-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0007_rename_serial_inversor_inversor_identificador_inversor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversor',
            name='huawei_devTypeId',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='huawei devTypeId'),
        ),
    ]
