# Generated by Django 5.2 on 2025-04-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0008_inversor_huawei_devtypeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversor',
            name='huawei_devTypeId',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='huawei devTypeId'),
        ),
        migrations.AlterUniqueTogether(
            name='generacioninversordiaria',
            unique_together={('id_proyecto', 'id_inversor', 'fecha_generacion_inversor_dia')},
        ),
    ]
