# Generated by Django 5.2 on 2025-04-26 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0009_alter_inversor_huawei_devtypeid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mppt',
            name='id_inversor',
        ),
        migrations.RemoveField(
            model_name='mppt',
            name='id_proyecto',
        ),
        migrations.CreateModel(
            name='Granular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_granular', models.CharField(default='', max_length=100, verbose_name='serial del granular')),
                ('tipo_granular', models.CharField(default='', max_length=100, verbose_name='tipo de granular')),
                ('id_inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.inversor')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.proyecto', verbose_name='nombre del proyecto')),
            ],
            options={
                'unique_together': {('id_proyecto', 'id_inversor', 'serial_granular')},
            },
        ),
        migrations.CreateModel(
            name='GeneracionGranularDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energia_generada_granular_dia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='energía por mppt generada en el día')),
                ('fecha_generacion_granular_dia', models.DateField(verbose_name='fecha de generación por mppt')),
                ('id_inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.inversor')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.proyecto', verbose_name='nombre del proyecto')),
                ('id_granular', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='solarData.granular')),
            ],
        ),
        migrations.DeleteModel(
            name='GeneracionMPPTDiaria',
        ),
        migrations.DeleteModel(
            name='MPPT',
        ),
    ]
