# Generated by Django 5.2 on 2025-05-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0010_remove_mppt_id_inversor_remove_mppt_id_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='capacidad_instalada_ac',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='capacidad instalada AC'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='capacidad_instalada_dc',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='capacidad instalada DC'),
        ),
    ]
