# Generated by Django 5.2 on 2025-06-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0011_proyecto_capacidad_instalada_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcasinversores',
            name='informacion_granular',
            field=models.BooleanField(default=True, verbose_name='tiene información de granular'),
        ),
    ]
