# Generated by Django 5.2 on 2025-07-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0012_marcasinversores_informacion_granular'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversor',
            name='capacidad_inversor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='capacidad del inversor (kW)'),
        ),
    ]
