# Generated by Django 5.2 on 2025-07-08 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0013_inversor_capacidad_inversor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(max_length=100, unique=True, verbose_name='nombre del departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=100, verbose_name='nombre de la ciudad')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarData.departamento', verbose_name='departamento')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'unique_together': {('nombre_ciudad', 'id_departamento')},
            },
        ),
    ]
