# Generated by Django 5.2 on 2025-07-08 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0015_auto_20250708_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='id_ciudad',
            field=models.ForeignKey(default=1125, on_delete=django.db.models.deletion.CASCADE, to='solarData.ciudad', verbose_name='ciudad'),
        ),
    ]
