# Generated by Django 5.2 on 2025-09-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0017_allow_null_energy_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generacionenergiadiaria',
            name='energia_generada_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='energía generada en el día'),
        ),
        migrations.AlterField(
            model_name='generaciongranulardiaria',
            name='energia_generada_granular_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='energía por mppt generada en el día'),
        ),
        migrations.AlterField(
            model_name='generacioninversordiaria',
            name='energia_generada_inversor_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='energía por inversor generada en el día'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='identificador_planta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='identificador de la planta (id)'),
        ),
    ]
