# Generated by Django 5.2 on 2025-10-27 22:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0018_alter_generacionenergiadiaria_energia_generada_dia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='apellido')),
                ('tipo_de_persona_natural_o_juridica', models.CharField(choices=[('Natural', 'Natural'), ('Jurídica', 'Jurídica')], max_length=20, verbose_name='tipo de persona')),
                ('company', models.CharField(blank=True, help_text='Solo para personas jurídicas', max_length=255, null=True, verbose_name='empresa')),
                ('id_colombia', models.CharField(help_text='Cédula de ciudadanía o NIT', max_length=50, unique=True, verbose_name='cédula/NIT')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('phone', models.CharField(help_text='Formato: +573001234567', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono colombiano válido (formato: +573001234567)', regex='^\\+573\\d{9}$')], verbose_name='teléfono')),
                ('firstname_cobranza', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre contacto cobranza')),
                ('lastname_cobranza', models.CharField(blank=True, max_length=100, null=True, verbose_name='apellido contacto cobranza')),
                ('email_cobranza', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='correo cobranza')),
                ('phone_cobranza', models.CharField(blank=True, help_text='Formato: +573001234567', max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono colombiano válido (formato: +573001234567)', regex='^\\+573\\d{9}$')], verbose_name='teléfono cobranza')),
                ('id_hs', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='HubSpot ID')),
                ('id_bubble', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Bubble ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='solarData.cliente', verbose_name='cliente'),
        ),
    ]
