# Generated by Django 5.2 on 2026-03-04 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0019_cliente_proyecto_id_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('id_bubble', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Bubble ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Instalador',
                'verbose_name_plural': 'Instaladores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='pid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Bubble ID'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_instalador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='solarData.instalador', verbose_name='instalador'),
        ),
    ]
