# Generated by Django 5.2 on 2026-03-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0020_instalador_proyecto_pid_proyecto_id_instalador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='pid',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='pid'),
        ),
    ]
