# Generated by Django 5.2 on 2026-03-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarData', '0021_alter_proyecto_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='pid',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='pid'),
        ),
    ]
