# Generated by Django 5.2 on 2025-04-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarDataFetch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversor',
            name='serial_inversor',
            field=models.CharField(default='', max_length=100, verbose_name='serial del inversor'),
        ),
        migrations.AddField(
            model_name='mppt',
            name='serial_mppt',
            field=models.CharField(default='', max_length=100, verbose_name='serial del mppt'),
        ),
    ]
