# Generated by Django 5.2 on 2025-04-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarDataFetch', '0002_inversor_serial_inversor_mppt_serial_mppt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generacioninversordiaria',
            name='id_inversor',
        ),
        migrations.RemoveField(
            model_name='generacioninversordiaria',
            name='id_proyecto',
        ),
        migrations.RemoveField(
            model_name='generacionmpptdiaria',
            name='id_inversor',
        ),
        migrations.RemoveField(
            model_name='generacionmpptdiaria',
            name='id_mppt',
        ),
        migrations.RemoveField(
            model_name='generacionmpptdiaria',
            name='id_proyecto',
        ),
        migrations.RemoveField(
            model_name='inversor',
            name='id_proyecto',
        ),
        migrations.RemoveField(
            model_name='mppt',
            name='id_inversor',
        ),
        migrations.RemoveField(
            model_name='mppt',
            name='id_proyecto',
        ),
        migrations.DeleteModel(
            name='GeneracionEnergiaDiaria',
        ),
        migrations.DeleteModel(
            name='GeneracionInversorDiaria',
        ),
        migrations.DeleteModel(
            name='GeneracionMPPTDiaria',
        ),
        migrations.DeleteModel(
            name='Inversor',
        ),
        migrations.DeleteModel(
            name='MPPT',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
