# Generated by Django 5.2 on 2026-03-04 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solarData', '0020_instalador_proyecto_pid_proyecto_id_instalador'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('fase', models.IntegerField(choices=[(1, 'Fase 1'), (2, 'Fase 2'), (3, 'Fase 3')], verbose_name='fase')),
                ('secuencia', models.IntegerField(verbose_name='secuencia')),
                ('tiene_fecha_reportada', models.BooleanField(default=False, verbose_name='tiene fecha reportada')),
            ],
            options={
                'verbose_name': 'Tipo de Hito',
                'verbose_name_plural': 'Tipos de Hito',
                'ordering': ['secuencia'],
            },
        ),
        migrations.CreateModel(
            name='HitoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField(blank=True, null=True, verbose_name='fecha programada')),
                ('fecha_real', models.DateField(blank=True, null=True, verbose_name='fecha real')),
                ('fecha_reportada', models.DateField(blank=True, null=True, verbose_name='fecha reportada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='solarData.proyecto', verbose_name='proyecto')),
                ('id_tipo_hito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='ops.tipohito', verbose_name='tipo de hito')),
            ],
            options={
                'verbose_name': 'Hito de Proyecto',
                'verbose_name_plural': 'Hitos de Proyecto',
                'ordering': ['pid', 'id_tipo_hito__secuencia'],
                'unique_together': {('pid', 'id_tipo_hito')},
            },
        ),
    ]
